version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./mysql/.env
    ports:
      - 3306:3306
    expose:
       - 3306
    volumes:
      - vol:/var/lib/mysql


  app:
    build:
      context: .
      dockerfile: Dockerfile

    command: bash -c "python database/admin.py && python app/handle_msg.py"
    volumes:
      - .:/bot
    depends_on:
      - db
volumes:
      vol: